steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: '/workspace/express'

  # Step 2: Deploy to App Engine with specific service and version
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'app',
        'deploy',
        'app.yaml',
        '--quiet',
        #'--project=[YOUR_PROJECT_ID]',
       # '--version=${_ENV}-version-${SHORT_SHA}',
       # '--no-promote'
      ]
    dir: '/workspace/express'

# Substitutions for environment-specific settings
substitutions:
  _ENV: staging
